" Set title on X window
set title

" make plugins smoother (don't redraw while executing macros)
set lazyredraw

" Redifinition of map leader
let mapleader = ","

" Add a line under the cursor (reverse color)
set cursorline

" Behaviors
set nocompatible
set encoding=utf-8
set backspace=indent,eol,start
set autoindent                  " Always set autoindenting on
set copyindent                  " copy the previous indentation on autoindenting
set ruler                       " Always show current positions along the bottom
set number                      " turn on line numbers

set nobackup                    " Don't make a backup before overwriting a file
set nowritebackup               " And again.
set noswapfile                  " Use an SCM instead of swap files

set shell=zsh                   " Use Zsh as default shell
set wildmenu                    " Enhanced command line completion.
set wildignore=.svn,CVS,.git,.hg,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif,*.pyc,*.pyo,*/zend/** " Ignore certain files

" redefine tabs
set expandtab       " no real tabs please!
set shiftwidth=2    " auto-indent amount when using cindent, >>, << and stuff
                    " like that
set softtabstop=2   " when hitting tab or backspace, how many spaces should a
                    " tab be (see expandtab)
set tabstop=2       " real tabs should be 2

set list
set listchars=tab:▸\ , " display special chars for tabs

set complete=.,w,b,u,t,i,k~/.vim/syntax/php.api

set scrolloff=5     " Keep x line for scope while scrolling
set sidescrolloff=5

set formatoptions+=or " see http://stackoverflow.com/questions/3298820/vim-phpdoc-multiline-comment-autoindent/3303017#3303017
set wrap            " long lines wrap and continue to the next line


" Search
"=======

set hlsearch        " Highlight search matches
set incsearch       " ...dynamically as they are typed.
" Clear search highlight
map <silent> <C-H> :let @/=""<CR>:echo "Cleared search register."<cr>

" These two options, when set together, will make /-style searches
" case-sensitive only if there is a capital letter in the search expression.
" *-style searches continue to be consistently case-sensitive.
set ignorecase
set smartcase

" Enable syntax highlighting
syntax on


" Bundles
"========

filetype off                  " required by vundle

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Plugin 'gmarik/vundle'

" My bundles
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'altercation/vim-colors-solarized'
Plugin 'ervandew/supertab'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/syntastic'
Plugin 'K-Phoen/vim-xdebug'
Plugin 'Shougo/neocomplcache'
Plugin 'spf13/PIV'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'godlygeek/tabular'

" Puppet plugins
Plugin 'puppetlabs/puppet-syntax-vim'

" Go plugins
Plugin 'fatih/vim-go'

filetype plugin indent on     " required!


" Theme setup
"============

let &t_Co=256         " force the 256-color mode
let g:solarized_termcolors=256
set background=dark
colorscheme solarized


" Custom mappings
"============

" Highlight unwanted spaces
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd BufWinLeave * call clearmatches()

" have Vim jump to the last position when reopening a file
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif

" Toggle line numbers and fold column for easy copying:
nnoremap <C-l> :set nonumber!<CR>:set foldcolumn=0<CR>

" Trim trailing spaces
map <leader>t :%s/\s\+$<CR>

" Start a substitute
map <leader>s :%s/

" Start a search
map <leader>h /<C-r>=expand("<cword>")<CR>

" Pull word under cursor into LHS of a substitute (for quick search and
" replace)
nmap <leader>S :%s/<C-r>=expand("<cword>")<CR>/

" Sudo to write
command W w !sudo tee % > /dev/null

" edit vimrc in a new tab
nnoremap <leader>ev :tabnew $MYVIMRC<CR>

" http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
" F2 = toggle paste mode
nnoremap <F2> :set invpaste paste?<Enter>
imap <F2> <C-O><F2>
set pastetoggle=<F2>


" Plugin specifics
"=================

" Tabular
map <leader>a :Tabularize/
vmap <Leader>a= :Tabularize /=><CR>

" vim-airline
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline_theme = 'powerlineish'

" tagbar
let g:tagbar_left = 1           " display the tagbar on the left side
set updatetime=500              " show tags' prototype after 500 milliseconds
let g:tagbar_width = 25         " width in characters of the tagbar
let g:tagbar_autoshowtag = 1    " always show the current tag in the tagbar
let g:tagbar_autofocus = 1      " the cursor will move to the Tagbar window when it is opened.
nnoremap <silent> <F10> :TagbarToggle<CR>

" Syntastic
let g:syntastic_auto_loc_list = 1                       " auto open/close the errors list
let g:syntastic_quiet_messages = {'level': 'warnings'}  " don't want warnings to be displayed

" Ctags
set tags=./tags;/,~/.vimtags,tags,vendor.tags

" ctrlp
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\.git$\|\.hg$\|\.svn$',
    \ 'file': '\.exe$\|\.so$\|\.dll$' }
let g:ctrlp_clear_cache_on_exit = 0

" OmniComplete
if has("autocmd") && exists("+omnifunc")
    autocmd Filetype *
        \if &omnifunc == "" |
        \setlocal omnifunc=syntaxcomplete#Complete |
        \endif
endif

hi Pmenu  guifg=#000000 guibg=#F8F8F8 ctermfg=black ctermbg=Lightgray
hi PmenuSbar  guifg=#8A95A7 guibg=#F8F8F8 gui=NONE ctermfg=darkcyan ctermbg=lightgray cterm=NONE
hi PmenuThumb  guifg=#F8F8F8 guibg=#8A95A7 gui=NONE ctermfg=lightgray ctermbg=darkcyan cterm=NONE

" PIV
let g:DisableAutoPHPFolding = 1
let g:PIVAutoClose = 0

" neocomplcache
let g:acp_enableAtStartup = 0
let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_camel_case_completion = 1
let g:neocomplcache_enable_smart_case = 1
let g:neocomplcache_enable_underbar_completion = 1
let g:neocomplcache_enable_auto_delimiter = 1
let g:neocomplcache_max_list = 10
let g:neocomplcache_enable_auto_select = 0
let g:neocomplete#force_overwrite_completefunc = 1

" Define dictionary.
let g:neocomplcache_dictionary_filetype_lists = {
            \ 'default' : '',
            \ 'vimshell' : $HOME.'/.vimshell_hist',
            \ 'scheme' : $HOME.'/.gosh_completions'
            \ }

" Define keyword.
if !exists('g:neocomplcache_keyword_patterns')
    let g:neocomplcache_keyword_patterns = {}
endif
let g:neocomplcache_keyword_patterns._ = '\h\w*'

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete

" Enable heavy omni completion.
if !exists('g:neocomplcache_omni_patterns')
    let g:neocomplcache_omni_patterns = {}
endif
let g:neocomplcache_omni_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
let g:neocomplcache_omni_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
let g:neocomplcache_omni_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'
let g:neocomplcache_omni_patterns.ruby = '[^. *\t]\.\h\w*\|\h\w*::'

" git gutter
highlight clear SignColumn

" Read vim config defined in files
set modeline
set modelines=1
