vim.opt.ignorecase = true     -- ignore case in search patterns
vim.opt.smartcase = true      -- smart case
vim.opt.smartindent = true    -- make indenting smarter again
vim.opt.autoindent = true     -- indent a new line the same amount as the line just typed
vim.opt.swapfile = false      -- don't create swapfiles
vim.opt.number = true         -- set numbered lines
vim.opt.undofile = true       -- enable persistent undo
vim.opt.signcolumn = "yes"    -- always show the sign column to avoid jumps when it appears/disappears
vim.opt.tabstop=4             -- number of columns occupied by a tab 
