# Path to your oh-my-zsh configuration.
export ZSH=$HOME/Config/zsh/oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="kphoen"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# quelques préférences
export EDITOR=/usr/bin/vim
export PATH=$PATH:~/sdk_android/tools
export PAGER=most

# des alias utiles
alias aptupgrade='sudo aptitude update && sudo aptitude safe-upgrade'
alias grep='grep --color=auto'
alias lh='ls -lh --color=auto'

alias ssvps='ssh kevin@46.4.131.201 -p 2001'
alias ssovh='ssh kevin@46.105.6.226'
alias ssh-x='ssh -c arcfour,blowfish-cbc -XC'

#alias dual_screen='xrandr --output VGA1 --mode 1280x1024 --same-as LVDS1'
#alias mono_screan='xrandr --output LVDS1 --mode 1024x600'

alias a2restart='sudo /etc/init.d/apache2 restart'
alias a2reload='sudo /etc/init.d/apache2 reload'
alias n2restart='sudo /etc/init.d/nginx restart'
alias n2reload='sudo /etc/init.d/nginx reload'

# git
alias gpl='git pull'
alias gps='git push'
alias gst='git status'
alias gci='git commit'

# petit hack pour faire fonctionner les raccourcis CTRL-LEFT et CTRL-RIGHT
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
